### ISSUE TITLE
Psi not decaying inside the barrier

### ISSUE THREAD

**Issue by manugaurdl** [labay11/tunneling-simulation#2]
Hey there, i am using your tunneling simulation. However the code psi doesn't seem to decay once it  enters the barrier.
I put
height of the barrier in eV = 5 
half length of the box in nm= 10 
half length of the barrier in nm=1 
kick in eV=5 center of the gaussian= 3 
size of the gaussian= 2.5
![Figure_2](https://user-images.githubusercontent.com/73697625/98672383-bb953700-237b-11eb-877a-322d2a913fd5.png)
![Figure_1](https://user-images.githubusercontent.com/73697625/98672387-bcc66400-237b-11eb-8238-2ab482f6dcb8.png)

**Comment by labay11** [comment]
There was a small error in the order of parameters which I fixed in the latest commit.

However, i also notice that it is not giving good results when the energy of the kick is close to `V0`, the simulation works well but the estimated energy does not. I will have to look into this.

A comment regarding the size of the Gaussian, I think it is too big and it might fall into the barrier, either choose a smaller width such that initially the wave packed is completely in one of the sides or move the center to the right (maybe 5 or 6 will do).

**Comment by manugaurdl** [comment]
Making the size 0.4 worked. Thanks!!
